-- MySQL Script generated by MySQL Workbench
-- 06/19/17 12:33:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema GestAbsences
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GestAbsences` ;

-- -----------------------------------------------------
-- Schema GestAbsences
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GestAbsences` DEFAULT CHARACTER SET utf8 ;
USE `GestAbsences` ;

-- -----------------------------------------------------
-- Table `GestAbsences`.`equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestAbsences`.`equipe` ;

CREATE TABLE IF NOT EXISTS `GestAbsences`.`equipe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NULL,
  `id_responsable` INT NULL,
  `id_hierarchie` INT NULL,
  `id_backup` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipes_equipe_idx` (`id_hierarchie` ASC),
  INDEX `fk_equipes_employe_idx` (`id_responsable` ASC),
  INDEX `fk_equipe_employe2_idx` (`id_backup` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestAbsences`.`service_rh`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestAbsences`.`service_rh` ;

CREATE TABLE IF NOT EXISTS `GestAbsences`.`service_rh` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestAbsences`.`employe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestAbsences`.`employe` ;

CREATE TABLE IF NOT EXISTS `GestAbsences`.`employe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NULL,
  `prenom` VARCHAR(100) NULL,
  `matricule` VARCHAR(45) NULL,
  `nb_ca` INT NULL,
  `nb_rtt` INT NULL,
  `nb_rc` INT NULL,
  `id_equipe` INT NULL,
  `id_service_rh` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employes_equipe_idx` (`id_equipe` ASC),
  INDEX `fk_employes_service_rh_idx` (`id_service_rh` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestAbsences`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestAbsences`.`type` ;

CREATE TABLE IF NOT EXISTS `GestAbsences`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestAbsences`.`statut`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestAbsences`.`statut` ;

CREATE TABLE IF NOT EXISTS `GestAbsences`.`statut` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NULL,
  `code` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestAbsences`.`absence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestAbsences`.`absence` ;

CREATE TABLE IF NOT EXISTS `GestAbsences`.`absence` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num_demande` INT NULL,
  `debut` DATE NULL,
  `fin` DATE NULL,
  `commentaire` LONGTEXT NULL,
  `id_employe` INT NULL,
  `id_type` INT NULL,
  `id_statut` INT NULL,
  `id_service_rh` INT NULL,
  'date_relance' DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_absences_employe_idx` (`id_employe` ASC),
  INDEX `fk_absences_type_idx` (`id_type` ASC),
  INDEX `fk_absences_statut_idx` (`id_statut` ASC),
  INDEX `fk_absences_service_rh_idx` (`id_service_rh` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestAbsences`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestAbsences`.`role` ;

CREATE TABLE IF NOT EXISTS `GestAbsences`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valeur` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestAbsences`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestAbsences`.`user` ;

CREATE TABLE IF NOT EXISTS `GestAbsences`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(100) NULL,
  `id_employe` INT NULL,
  `id_role` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_employe_idx` (`id_employe` ASC),
  INDEX `fk_users_role_idx` (`id_role` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `GestAbsences`.`num_demande`
-- -----------------------------------------------------

CREATE TABLE `gestabsences`.`num_demande` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NULL,
  PRIMARY KEY (`id`));



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
