-- MySQL Script generated by MySQL Workbench
-- 04/28/17 09:17:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema GestAbsences
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GestAbsences` ;

-- -----------------------------------------------------
-- Schema GestAbsences
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GestAbsences` DEFAULT CHARACTER SET utf8 ;
USE `GestAbsences` ;

-- -----------------------------------------------------
-- Table `GestAbsences`.`Equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestAbsences`.`Equipe` ;

CREATE TABLE IF NOT EXISTS `GestAbsences`.`Equipe` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(100) NULL,
  `id_Responsable` INT UNSIGNED NOT NULL,
  `id_EquipeMere` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestAbsences`.`ServiceRH`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestAbsences`.`ServiceRH` ;

CREATE TABLE IF NOT EXISTS `GestAbsences`.`ServiceRH` (
  `id` INT NOT NULL,
  `Email` VARCHAR(255) NULL,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestAbsences`.`Employe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestAbsences`.`Employe` ;

CREATE TABLE IF NOT EXISTS `GestAbsences`.`Employe` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(100) NULL,
  `Prenom` VARCHAR(100) NULL,
  `Matricule` VARCHAR(45) NULL,
  `NbCP` INT NULL,
  `NbRTT` INT NULL,
  `NbRC` INT NULL,
  `ReliquatCA` INT NULL,
  `ReliquatRTT` INT NULL,
  `id_Equipe` INT UNSIGNED NOT NULL,
  `id_ServiceRH` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestAbsences`.`Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestAbsences`.`Type` ;

CREATE TABLE IF NOT EXISTS `GestAbsences`.`Type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestAbsences`.`Statut`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestAbsences`.`Statut` ;

CREATE TABLE IF NOT EXISTS `GestAbsences`.`Statut` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestAbsences`.`Absence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestAbsences`.`Absence` ;

CREATE TABLE IF NOT EXISTS `GestAbsences`.`Absence` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Debut` DATE NULL,
  `Fin` DATE NULL,
  `id_Employe` INT UNSIGNED NOT NULL,
  `id_Type` INT UNSIGNED NOT NULL,
  `id_Statut` INT UNSIGNED NOT NULL,
  `id_ServiceRH` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestAbsences`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestAbsences`.`Role` ;

CREATE TABLE IF NOT EXISTS `GestAbsences`.`Role` (
  `id` INT NOT NULL,
  `Role` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestAbsences`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestAbsences`.`User` ;

CREATE TABLE IF NOT EXISTS `GestAbsences`.`User` (
  `id` INT NOT NULL,
  `Email` VARCHAR(255) NULL,
  `Password` VARCHAR(100) NULL,
  `id_Employe` INT UNSIGNED NOT NULL,
  `id_Role` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
